apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80
    args: 
    - sleep
    - "1800"
    resources:
      limits:
        cpu: "1"
        memory: 128Mi
      requests:
        cpu: "0.5"
        memory: 64Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: html
    emptyDir:
      sizeLimit: 256Mi

